1   
```markdown
vagrant@server1:~/playbook$ ansible-playbook -i inventory/test.yml site.yml

PLAY [Print os facts] **************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Print OS] ********************************************************************************************************
ok: [localhost] => {
    "msg": "Ubuntu"
}

TASK [Print fact] ******************************************************************************************************
ok: [localhost] => {
    "msg": 12
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
2   
```markdown
vagrant@server1:~/playbook$ cat group_vars/all/examp.yml
---
  some_fact: 12
vagrant@server1:~/playbook$ nano group_vars/all/examp.yml
vagrant@server1:~/playbook$ ansible-playbook -i inventory/test.yml site.yml

TASK [Print fact] ******************************************************************************************************
ok: [localhost] => {
    "msg": "all default fact"
}
```
3   
если я правильно  понял, то нужно скачать docker, если нет , то подскажаите что надо сделать , 
потому что в 4 задание ошибку выдает и так же подскажиет сразу 5 задание , я так понимаю  , над просто к deb добавить "default fact" 
```markdown

```
4   
```markdown
vagrant@server1:~/playbook$ ansible-playbook -i inventory/prod.yml site.yml

PLAY [Print os facts] *************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
fatal: [centos7]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1657969208.836405-23212766236013 `\" && echo ansible-tmp-1657969208.836405-23212766236013=\"` echo ~/.ansible/tmp/ansible-tmp-1657969208.836405-23212766236013 `\" ), exited with result 1", "unreachable": true}
fatal: [ubuntu]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1657969208.8467803-18415638863094 `\" && echo ansible-tmp-1657969208.8467803-18415638863094=\"` echo ~/.ansible/tmp/ansible-tmp-1657969208.8467803-18415638863094 `\" ), exited with result 1", "unreachable": true}

PLAY RECAP ************************************************************************************************************
centos7                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
ubuntu                     : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```